### ISSUE TITLE
用法跟dva差不多诶

### ISSUE THREAD

**Issue by hldzlk** [mirrorjs/mirror#1]
有没有什么比较明显的区别？

**Comment by hldzlk** [comment]
有没有什么比较明显的区别？

**Comment by llh911001** [comment]
`model` 方法毫无疑问来源于 dva。

与 dva 不同的地方在于：

1. 不用初始化 app 实例了（因此无法多应用实例）；
2. redux 这块，action 的 dispatch 方式不同，不用 saga（但支持自定义使用 middleware）；
3. 对路由的处理更简单，完全按照 react-router 4 的方式定义，没有创造新的复杂性。

更多可以查看文档。

**Comment by linkgod** [comment]
@llh911001 是否可以认为是更轻量的dva？

**Comment by hldzlk** [comment]
@llh911001 谢谢回复

**Comment by liSong5713** [comment]
mirrorx 优点在于极大简化了 组件与model的交互，effects方法又返回了promise，流程的简洁很多，mirrorx只初始化一次，actions 中包含了所有的models，这样在也不用yield select...,model中更集中了业务逻辑！赞
