### ISSUE TITLE
希望能实现和dva-loading类似的模块

### ISSUE THREAD

**Issue by Gavinchen92** [mirrorjs/mirror#10]
dva-loading极大的简化了loading状态管理

**Comment by ouxu** [comment]
利用 hook 中间件模拟吧
`mirror.hook((action, getState) => {
  NProgress.start()
  setTimeout(() => NProgress.done(), 1000)
})
`

**Comment by Gavinchen92** [comment]
还是有去别的

**Comment by llh911001** [comment]
这个其实很简单。

如果 `effects` 中的方法返回的是一个 `promise`，那么 `actions.<modelName>.<effectName>` 调用后返回的就是这个 `promise`：

```js
effects: {
  async addAsync(data, getState) {
    const {app} = getState()
    const res = await Promise.resolve(app + data)
    actions.app.add(res)
    return res
  }
}
```

然后可以这样操作，在 dispatch 之前，显示 loading；当这个 `promsie` resolve/reject 后隐藏：

```js

showLoading()
actions.app.addAsync(42)
  .then(res =>  hideLoading())
  .catch(err => hideLoading())
```

事实上，`actions.<modelName>.<effectName>` 返回的就是 `effects` 中定义的方法所返回的结果。

**Comment by Gavinchen92** [comment]
这个loading是整个页面的吧, 而且每次都要自己去隐藏很麻烦

**Comment by chakhsu** [comment]
一般除了首页需要整个页面loading外，别的页面很少会用到，因为已经有共用的组件，如布局组件， @llh911001 的例子已经很清晰了。

**Comment by Gavinchen92** [comment]
公共组件也只是提供了loading这个接口， 它的loading状态还是要认为赋值的， 用dva-loading的目的就是要精确到单个组件
