### ISSUE TITLE
history 包的引用方式发生改变，目前产生三个警告，需要升级写法

### ISSUE THREAD

**Issue by kvkens** [mirrorjs/mirror#104]
![image](https://user-images.githubusercontent.com/3817644/54576353-b8289b80-4a32-11e9-86dc-d0581d8884d6.png)

目前的引用写法
https://github.com/mirrorjs/mirror/blob/6cb447d158ba1b8791c2e79fff9c0901d9d26c88/src/router.js#L3

需要升级到提示给出的方式 @llh911001

**Comment by kvkens** [comment]
要不我修改下提交个pr吧?

**Comment by kvkens** [comment]
已经pr

**Comment by JoMartinezZhu** [comment]
已经安装了 mirrox  在使用 'history/createBrowserHistory 时 ，还需要 npm install history 吗？

**Comment by llh911001** [comment]
> 已经安装了 mirrox 在使用 'history/createBrowserHistory 时 ，还需要 npm install history 吗？

需要
