### ISSUE TITLE
关于action调用范围的疑问

### ISSUE THREAD

**Issue by ruixiu** [mirrorjs/mirror#14]
是否可以把同步action缩小调用范围，比如只能通过异步action进行调用。在我的一个项目中，所有数据请求都是通过异步action发起的，我不希望直接调用同步action更新state

**Comment by llh911001** [comment]
还是存在在业务代码中，直接调用“同步 action“的情况的。

如果将 action 这样限制了，如果你想直接调用一个”同步 action”，就没办法了。
