### ISSUE TITLE
为什么执行一下hook就会移除它

### ISSUE THREAD

**Issue by chakhsu** [mirrorjs/mirror#19]
如题~  

api文档关于`mirror.hook((action, getState) => {})`的描述太简单了，执行一下就移除？什么原理？看源码也找不到相应地方~

**Comment by llh911001** [comment]
执行后不会移除，返回的是一个将会移除它的函数。仔细看下文档哈。

**Comment by chakhsu** [comment]
我看英文文档，没有这段话~，文档描述非常含糊不清~
