### ISSUE TITLE
initialState是否可以考虑换成state

### ISSUE THREAD

**Issue by lensh** [mirrorjs/mirror#2]
给个小建议，就是可不可以把initialState换成state，这样会更简洁一点，写项目的的时候也更方便。而且vuex 也是用 state 来表示初始状态的，尽量保持一致吧。。。

**Comment by llh911001** [comment]
`state` 的确更为简洁，不过我们要考虑一下，因为这算是 breaking change 了。
可能会在下个大版本改掉，谢谢建议！
