### ISSUE TITLE
Example syntax for reducers

### ISSUE THREAD

**Issue by jonaswindey** [mirrorjs/mirror#20]
In the README, there's this syntax for reducers:

```js
  reducers: {
    increment(state) { return state + 1 },
    decrement(state) { return state - 1 }
  },
```

I would propose to change this to
```js
  reducers: {
    increment: state => state + 1,
    decrement: state => state - 1
  },
```

That way it's clear that they are methods and we can skip the return statement.
If you want to return an object you have to wrap it in ( )

**Comment by llh911001** [comment]
Yes, arrow functions are simpler. Thanks for advice, we'll consider updating that by next commit 😀
