### ISSUE TITLE
How can I specify <Router /> basename?

### ISSUE THREAD

**Issue by blairbodnar** [mirrorjs/mirror#22]
How can I specify a router basename?

With the `<BrowserRouter />` component in react-router v4, there is a [basename](https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string) prop:

```jsx
<BrowserRouter basename="/calendar" />
<Link to="/today"/> // renders <a href="/calendar/today">
```

Is there a way to access or use this in the <Router /> component provided in mirrorx?

```jsx
import mirror, {Router, render} from 'mirrorx'
render((
    <Router basename="/calendar"> // no basename prop... this doesn't work
        ...
    </Router>
), document.getElementById('foo'));

```

thanks! 😄

**Comment by llh911001** [comment]
Yeah, that's a problem currently, 'cause the `ConnectedRouter` provided by [react-router-redux](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) is a top-level Router which doesn't handle props like `basename` or `getUserConfirmation`.

We'll figure out this, thanks for response!

**Comment by blairbodnar** [comment]
Ah yeah, I see. Thanks! And great work with everything. I'm loving mirrorx so far 👍

**Comment by island205** [comment]
@blairbodnar you could pass an `history` instance to `Router`:

```js
import createHistory from 'history/createBrowserHistory'
import mirror, {Router, render} from 'mirrorx'

const history = createHistory({basename: '...'})
render((
    <Router history={history} >
        ...
    </Router>
), document.getElementById('foo'));

**Comment by blairbodnar** [comment]
@island205 Thanks! That works great!

**Comment by llh911001** [comment]
@blairbodnar It's done, now `Router` supports every prop `BrowserRouter` or `HashRouter` handles. Take a look at this [commit](https://github.com/mirrorjs/mirror/commit/8fed715ad1fc858731f741f0c48ba7e3d09ffcee), the latest version is v0.2.7.

**Comment by blairbodnar** [comment]
@llh911001 Awesome, thank you!
