### ISSUE TITLE
能否有一个类似dva的admin模板呢

### ISSUE THREAD

**Issue by wentao978** [mirrorjs/mirror#23]

**Comment by llh911001** [comment]
admin 模板具体指什么？如果是项目结构模板，可以看一下这个回应哈：https://github.com/mirrorjs/mirror/issues/5#issuecomment-323644786

**Comment by wentao978** [comment]
是个包含了登录退出，进去之后有路由侧边栏和主体内容的模板

**Comment by llh911001** [comment]
@wentao978 明白了。其实你可以看着自己用 mirror 实现一个哈，是个不错的练手项目呢

**Comment by llh911001** [comment]
@wentao978 写了一个类似 dva-user-dashboard 的例子：https://github.com/mirrorjs/user-dashboard-example
