### ISSUE TITLE
可以来个拆分model(单独目录)的例子吗

### ISSUE THREAD

**Issue by solarhell** [mirrorjs/mirror#25]
有些场景需要多组件共用model，如果在container内分别connect，总感觉不太好。

**Comment by icuke** [comment]
跟 dva 一样, 可以直接建一个 models 文件夹, 在 container 或者 components 里面注入

**Comment by liSong5713** [comment]
`app.model(model1),app.model(model2)`

**Comment by llh911001** [comment]
@solarhell 看一下 [user-dashboard](https://github.com/mirrorjs/user-dashboard-example) 这个示例项目。
