### ISSUE TITLE
路由上的hook怎么加

### ISSUE THREAD

**Issue by liSong5713** [mirrorjs/mirror#30]
mirrorx用的是rr4 ，但是没有暴露rr4的hook，请问怎么引入？

**Comment by llh911001** [comment]
指的是 `onEnter` 等 hook ？rr4 已经没有这些 hook 了呀

**Comment by liSong5713** [comment]
mirrorx 只暴露了
`Route
Switch
Redirect
Link
NavLink
`
,prompt还没有暴露。

**Comment by llh911001** [comment]
我们当时认为实现这种跳转前确认的功能，使用 `shouldComponentUpdate` 生命周期方法就行了，所以就没有暴露 `Prompt`（基于类似的考虑，我们也没有暴露 `withRouter`）。

不过假如你确实有需要的话，我们会在近期的发布中加上。

不过要注意的是，如果你不想使用默认的 `window.prompt`，那么你需要自己指定一下 [`getUserConfirmation`](https://github.com/ReactTraining/history#customizing-the-confirm-dialog)。

**Comment by liSong5713** [comment]
shouldComponentUpdate也可以实现,但是在语义和便捷度上,Prompt可能更好些！

**Comment by llh911001** [comment]
已经加上了。谢谢建议！
