### ISSUE TITLE
在监听Url变换时候是否在Model中添加subscriptions？

### ISSUE THREAD

**Issue by liSong5713** [mirrorjs/mirror#31]
如题,dva提供了类似subscriptions 用于监听url的变换从而进行一系列请求，然后将数据挂载在 model的 state上。但是mirrorx 获取数据时候可能要在组件didMount时候，然后再去定义一个方法去更新model state,两者对比各有各的好处，但是mirrorx是否可以增加像subscriptions的一个接口呢？

**Comment by chakhsu** [comment]
看一下 mirror.hook

**Comment by liSong5713** [comment]
mirror.hook 是监听action的，subscriptions是监听url的，业务场景不一样

**Comment by chakhsu** [comment]
```
以 key/value 格式定义 subscription。subscription 是订阅，用于订阅一个数据源，然后根据需要 dispatch 相应的 action。在 app.start() 时被执行，数据源可以是当前的时间、服务器的 websocket 连接、keyboard 输入、geolocation 变化、history 路由变化等等。

格式为 ({ dispatch, history }, done) => unlistenFunction。

注意：如果要使用 app.unmodel()，subscription 必须返回 unlisten 方法，用于取消数据订阅。
```
来自 [dva 文档](https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md)

请问从技术角度看，我看不出 mirror.hook 跟 dva的 subscriptions 有什么，下面举一个摸索的例子

从 examples 下的 simple-router，在`mirror.model({ ... })`下，加上下面代码即可实现与dva一样的subscriptions

```js
mirror.hook((action, getState) => {
  console.log(action)
  if (action.type === '@@router/LOCATION_CHANGE') {
    if(action.payload.pathname === "/topics"){
      actions.topics.add('1')
    }
  }
})
```

你可以本地测试跑一次~

**Comment by liSong5713** [comment]
我的业务场景这样的，在切换url的时候去fetch data然后更新model的state,用mirror.hook肯定可以实现state的添加，但是貌似用hook会有更多繁琐的步骤吧，直接就可以actions.app.add(data)，不用再去handel action 。我认为hook的场景更在于处理异常，mirrorx确实解耦了dva的model，可能让model职责更统一.

**Comment by chakhsu** [comment]
还好，并没有什么更多繁琐的步骤，定义一个hook来监听router的type，然后该干嘛就干嘛，不过mirror没有集成fetch这是真的，影响不大。前端异常还真的很少，除非充分不信任后端api，那也是全局状态去作处理就行了，属于后端思维过分考虑页端情况了

**Comment by liSong5713** [comment]
@chakhsu ，感谢指教！这个issue 我关掉啦
