### ISSUE TITLE
为什么这里要注释？

### ISSUE THREAD

**Issue by chakhsu** [mirrorjs/mirror#34]
https://github.com/mirrorjs/mirror/blob/5ca50318b4e045dc98c5e27475963c1ad771f75c/src/defaults.js#L3

跟文档描述有点不一致

> mirror.defaults is a pretty intuitive API, you use it to configure your Mirror app.
> 
> * options.initialState
> 
> Default: undefined

`options.initialState`如果默认是空对象，也比默认是`undefined`要强吧~

**Comment by llh911001** [comment]
没有关系的，看一下 Redux 的源码，`createStore` 时候传的 `preloadedState` 默认是 `undefined`。
