### ISSUE TITLE
Effects with Sagas & Subscriptions

### ISSUE THREAD

**Issue by ShMcK** [mirrorjs/mirror#35]
First of all, I'd just like to say I like a lot of the design decisions in Mirror.js. Great work, with many improvements over DVA. I'll continue writing with an assumption that you may be familiar with DVAs API.

I have two suggestions that I would like to help create to bring both **sagas with effects** & an improved form of **subscriptions** to mirror.js. I believe this can be done without adding much additional weight to mirror.js.

## 1. Effects using Sagas

One feature that remains missing is effects that run as sagas. 

Using Mirror, sagas can still be used, but not within effects (as they are not running sagas).

I'm not at all suggesting copying the way effects are done in DVA. In DVA saga effects are passed in as the second param. 

```js
  // within dva model
  effects: {
    *someEffect(action, effects) {
      effects.put({ type: 'someAction' })
    }
  }
```

This isn't really necessary, since saga effects can be imported. 

Note that I'm also not suggesting that `redux-saga` should become a dependency of mirror.js.

## 2. Subscriptions 

In DVA, subscriptions run within a model on startup. These can be used to load data on startup of a model, among other uses.

When using sagas, it would be more effective if you could launch saga **watchers** on startup. Watchers are generator functions that allow you to create action listeners that trigger other functions. They can really help to keep your models from entangling each other with calls.

This is a two step process in DVA, (subscription calls an effect, effect calls a watcher). In DVA subscriptions are not sagas, but I would like to be able to overwrite how subscriptions work to make them into sagas as well.

```js
// within dva model
subscriptions: {
  *watch() {
    // pause until a user is logged in
    yield take('authenticated')
    // listen for an action, and trigger an effect
    yield takeEvery('someAction', put({ type: 'doSomething' })
  }
}
```

This would create a very elegant and clear way to use sagas within a model.

Subscriptions could made to check if the function is a generator or not. Generators could run using a saga, whereas functions could run as normal.

## Proposal

What I would like to do is be able to overwrite how effects are handled as a default option. I'd also like to add subscriptions with an optional overwrite.

For example:

```js
mirror.defaults({
  effects: customEffectsHandler, // overwrite existing function
  subscriptions: customSubscriptionHandler, // create additional function that runs on startup
  middlewares: [sagaMiddleware],
})
```

I'd be happy to put in a PR for review, as well as to publish and maintain a `mirror-saga` module separately.

**Comment by llh911001** [comment]
Great thinking, thanks!

To add full support to `redux-saga` is really a great idea, though our original intention was to avoid the use of saga, lol.

So we still need to think through the necessity of it, thanks again!

**Comment by ShMcK** [comment]
I should be clear. I'm not suggesting mirror add sagas. 

I'd just like Mirror to have a flexible enough API so that a separate add-on could be created for anyone who would like to use sagas. 

```js
import mirrorSaga from 'mirrorSaga'

mirror.defaults(mirrorSaga(options))
```

Sagas come with a lot of benefits, its worth considering.

**Comment by madisvain** [comment]
I'd like to support the idea of having Sagas as an option for mirrors.

**Comment by llh911001** [comment]
Yes, [#37](https://github.com/mirrorjs/mirror/pull/37) was merged!

**Comment by ShMcK** [comment]
I've created one more PR to clean up a blocking issue in the previous PR. #43 

I've also created a separate package which contains [Mirror-Saga](https://github.com/ShMcK/mirror-saga), a plugin for adding sagas. 

## Setup

```js
import mirrorSaga from 'mirror-saga'

mirror.defaults(mirrorSaga())

// OR optionally pass in mirror default options
// mirror.defaults(mirrorSaga(options))
```

## Example

Add model effects as generators (*function) and they will be treated as sagas by middleware.

```js
mirror.model({
  name: 'app',
  // ...
  effects: {
    *runASaga(payload) {
      yield delay(1000)
      yield actions.app.doSomething(payload)
    },
  }
})
```

Effects that are not generators will run normally.

```js
export default {
  name: 'app',
  effects: {
    // runs as async function
    async incrementAsync() {
      await asyncDelay(1000)
      actions.app.increment()
    },
    // runs as saga
    *incrementAsyncSaga() {
      yield delay(1000)
      yield actions.app.increment()
    },
  }
}
```
