### ISSUE TITLE
反馈：示例中simple-router路由404

### ISSUE THREAD

**Issue by source2git** [mirrorjs/mirror#39]
\examples\simple-router\public\index.html中入口app.js引用为相对路径：
`<script src="app.js"></script>`
会导致地址栏直接输入路由地址（例如：localhost:8000/about/balabala）时404，建议改为绝对路径：
`<script src="/app.js"></script>`

**Comment by llh911001** [comment]
404 的原因不是 `app.js` 脚本的路径问题，而是 `history` 对象的问题。

示例中的 `history` 是 [hash history](https://github.com/mirrorjs/mirror/blob/master/docs/api.md#-optionshistorymode)（[代码](https://github.com/mirrorjs/mirror/blob/master/examples/simple-router/src/index.js#L6-L8)），路径中会有 `#`，你直接输入这样的路径访问的确会 404。

试着输入类似 http://localhost:8000/#/about 这样的路径看看。

**Comment by source2git** [comment]
我忘记说了，我一开始就改成browser history了
`mirror.defaults({
  historyMode: 'browser'
})`

**Comment by source2git** [comment]
dev-server会把所有path都定向到index.html，但是里面的app.js如果写相对路径就会向错误的地址请求资源导致404。
比如：访问localhost:8000/topics/0请求的是localhost:8000/topics/app.js，这个地址返回实际是index.html，控制台会报js语法错误。

**Comment by llh911001** [comment]
了解了。

之前是我理解有误。现已改正提交，你查看一下。
