### ISSUE TITLE
how about export the api to just build a redux store functional like jumpstate?

### ISSUE THREAD

**Issue by chenkaiC4** [mirrorjs/mirror#40]
Nice Work! The api is so sweet and backended by a good design.

I wanna to have a try with mirror for its clean design and code. But, as now i am fousing at a RN project, the router picked is `react-navigation`, and i don't want to change to `react-router-native`. So, i think just use mirror as a state manager is more convenient to me(like `jumpstate`). I have read the code. the `index.js` not export `state` created by mirror. and the process of create state is in `render.js`, however, adding a `getState` api to init state and supply to Provider of `react-redux` in my current RN project is what i want.

how about this suggestion?

**Comment by llh911001** [comment]
So, an exported `getState` is what you need, right?

**Comment by chenkaiC4** [comment]
@llh911001  yes, i send a PR for this #41 .

**Comment by llh911001** [comment]
Following the API to create a state manager is totally fine and encouraged.

The reason we integrate `Router` and export an enhanced `render` API is to provide an opinionated way to write React/Redux apps, so flexibility is lost to some extent.

Perhaps a state manager and render/router part are decoupled in the future, but for now, we prefer not to exposing a `createStore` API.
