### ISSUE TITLE
Add custom reducer

### ISSUE THREAD

**Issue by vanhtuan0409** [mirrorjs/mirror#42]
I think this project is great, is reduce a lot of boilerplate from redux
But 1 thing that should be improved is the ability to add custom reducer. Currently, I want to apply [redux-form](http://redux-form.com/) into my project but I have no method to attach redux form reducer into mirrorx
I think you can expose an API similar to `hook` that add custom reducer
Thank you for your work

**Comment by llh911001** [comment]
What about adding an option in `mirror.defaults` to specify it, like:

```js
import mirror from 'mirrorx'
import { reducer as formReducer } from 'redux-form'

mirror.defaults({
  reducers: {
    form: formReducer
  }
})
```

**Comment by vanhtuan0409** [comment]
I think it will do
But I did not see that option for reducer in API document

**Comment by llh911001** [comment]
It's not implemented yet, will do in the next few days.

**Comment by llh911001** [comment]
@vanhtuan0409 It's done by @madisvain , much thanks to @madisvain !
