### ISSUE TITLE
Releases & Changelog

### ISSUE THREAD

**Issue by ShMcK** [mirrorjs/mirror#48]
It would be helpful to:

## Publish Releases on Github

[Publishing releases on Github](https://help.github.com/articles/creating-releases/) makes it easy to see what the latest and previous releases are, without having to go to NPM. To do this, you'll also have to `git tag` versions of Mirror.

## Add a Changelog

As a project evolves, its helpful to know what has changed - especially any possible breaking changes. You might want to consider adding a [CHANGELOG.md](http://keepachangelog.com/en/0.3.0/). This could be automated
 with a variety of tools, such as [github-changelog-generator](https://skywinder.github.io/github-changelog-generator/).

---

If this seems like too much work, don't worry about it. But if you'd like any assistance, I'm happy to help.

**Comment by llh911001** [comment]
Been busy for the last week 😂

Yes, releases and CHANGELOG is necessary, I'm working on it.

**Comment by ShMcK** [comment]
Oh, good stuff. Thanks :)

I’m on a trip this weekend, but I’ll send you the mostly finished presentation before Monday. We made quite a few changes this week.

I may also be able to finish the router. I’m having issues with creating a submodule when bundling with Webpack. Will figure it out.

- Shawn

**Comment by llh911001** [comment]
I should remind you that I've made a change about `Router` to handle props like `basename` etc, so your current work on submodule router might be influenced.

**Comment by llh911001** [comment]
Hi @ShMcK , [Change log](https://github.com/mirrorjs/mirror/blob/master/CHANGES.md) is finally added :)
