### ISSUE TITLE
是否可以考虑也提供类似dva的项目结构模板呢

### ISSUE THREAD

**Issue by sundaypig** [mirrorjs/mirror#5]
希望可以看到对mirror项目的最佳实践

**Comment by wutaizeng** [comment]
+1

**Comment by llh911001** [comment]
之所以没有提供项目模版，是因为 Mirror 足够简单，不需要复杂的项目结构；只需要使用类似 [create-react-app](https://github.com/facebookincubator/create-react-app) 这样的脚手架工具生成一个项目，然后安装 Mirror 的依赖即可（这也是我们推荐的方式，因为我们觉得没有必要再写一个类似 `mirror-cli` 的命令行工具了，这样会引入更多的复杂度）。

如果一定要有一个“最佳实践”，我们觉得以下这种非常简单的结构即可：
```sh
$ tree src/
src/
├── components    # 展示型组件目录
│   ├── App.js
│   └── Count.js
├── containers    # 容器型组件目录
│   └── Count.js
├── models        # 存放所有的 model 对象，最终被 `mirror.model` 接口调用
│   └── count.js
└── index.js      # 入口文件，启动 app
```
> 注意这里没有考虑 CSS 的问题——CSS 的自由度很大，应该由开发者自行决定。

甚至上面的 `models` 目录都不是必需的，你可以在容器型组件中直接创建并注入 `model`，就像我们的 [Todo 示例项目](https://github.com/mirrorjs/mirror/tree/master/examples/todo) 那样。
