### ISSUE TITLE
Roadblock to Mirror-Loading

### ISSUE THREAD

**Issue by ShMcK** [mirrorjs/mirror#50]
I'd like to create a 'mirror-loading' package, similar to [dva-loading](https://github.com/dvajs/dva/tree/master/packages/dva-loading). Basically it provides free "loading" indicators when effects are triggered or completed.

## Problem

There should be a way in mirror to tell if an action handler is a "reducer" or an "effect". This way, "mirror-loading" can work with effects only.

## Possible Solutions

1. Expose the "effects" object in Mirror.

This would be the simplest solution, but it doesn't seem elegant to expose more than necessary. Effects are already included in the list of actions.

```js
// index.js
export default {
  /* ... */
  effects,
  /* ... */
}
```

2. Tag effect action handlers as "effects"

This would allow filtering over `actions` to find which are effects. A rough outline of an example below:

```js
// model.js
  filterReducers(reducers) {
   /* .... */
    acc[action].prototype.effect = true
   /* ... */
  }
```

3. Something else ?

**Comment by vanhtuan0409** [comment]
Is there any progress on this 😄 
I would love to see this package

**Comment by llh911001** [comment]
@vanhtuan0409 Currently, you could add a `loading` property for your model, then in your effects, set it to `true` before fetching and to `false` after fetching. [Here](https://github.com/mirrorjs/user-dashboard-example/blob/master/src/models/users.js#L8) is a demonstration.

An out-of-the-box loading requires a global `loading` state in Mirror, though it's not too hard to implement.

**Comment by ShMcK** [comment]
I've made a demo of a loading package. I'll try to finish it this weekend. [mirror-loading](https://github.com/ShMcK/mirror-loading)
