### ISSUE TITLE
Unresolved variable

### ISSUE THREAD

**Issue by mfma** [mirrorjs/mirror#53]
在Webstorm中不识别actions后的model，有办法解决吗？

![image](https://user-images.githubusercontent.com/5546094/30361887-f83fff24-988b-11e7-85d7-f6b069c6354a.png)

**Comment by llh911001** [comment]
这个可能暂时无法解决，因为 `actions` 上的属性是间接添加的，编辑器不一定能追踪到。

不过我搜到了几个结果，供你参考：https://intellij-support.jetbrains.com/hc/en-us/community/posts/207035685-Eliminating-unresolved-variable-warnings-on-external-package-json-objects?sort_by=votes
