### ISSUE TITLE
Export react-router-redux navigation

### ISSUE THREAD

**Issue by vanhtuan0409** [mirrorjs/mirror#57]
I want to make some route redirect outside of component so can you export history or a push function from react-router-redux

**Comment by llh911001** [comment]
Ah, maybe you're looking for the `actions.routing.push` or `actions.routing.replace` methods, take a look at the [docs](https://github.com/mirrorjs/mirror/blob/master/docs/api.md#-actionsrouting).

**Comment by vanhtuan0409** [comment]
Wow thank you very much
I didn't see that.
Very much appreciate your work
