### ISSUE TITLE
支持react native吗？

### ISSUE THREAD

**Issue by ruixiu** [mirrorjs/mirror#6]
是否支持react native

**Comment by llh911001** [comment]
暂时还不支持哦，主要是没有引入 [react-router-native](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-native)。

**Comment by ruixiu** [comment]
fork以后修改为自己需要的，可以吧。因为这觉得你的这种思路真的特别好，只是我目前在做react native，所以不需要router部分

**Comment by llh911001** [comment]
完全可以啊，Mirror 本身思路来源于 dva 和 jumpstate。

很惭愧，就做了一点微小的工作。
