### ISSUE TITLE
路由引用疑问

### ISSUE THREAD

**Issue by BoyuZhou** [mirrorjs/mirror#61]
在react-router v4中，react-router-dom包含了react-router的api，为什么要同时引用两个？

**Comment by llh911001** [comment]
引用了两个其实没有特殊的理由，一开始是认为主要引 react-router 中的组件，其他的类似 `NavLink` 只来自于 react-router-dom ，那么就从它引。也没多想 react-router-dom 包含了所有 react-router 的 API。后面会把 react-router 的依赖去掉。

谢谢指出！
