### ISSUE TITLE
update peerDependencies for react v16 released.

### ISSUE THREAD

**Issue by xialvjun** [mirrorjs/mirror#64]
```json
{
  "peerDependencies": {
    "react": ">=15",
    "react-dom": ">=15",
    "prop-types": ">=15"
  },
}
```

**Comment by llh911001** [comment]
下次提交的时候改哈 😀

**Comment by yurizhang** [comment]
我今天 也遇到这个了：warning "mirrorx@0.2.7" has incorrect peer dependency "react@^15.0.0"

**Comment by xialvjun** [comment]
都快一个月没更新这库了。。。虽然功能已经完整的库本身确实也不需要怎么更新。。。

**Comment by llh911001** [comment]
好的，今天会更新一版。谢谢提醒！

最近主要是在做解耦 router 的测试，大家有兴趣可以看一下 `feature/router` 分支。

**Comment by xialvjun** [comment]
谢谢。。。说到 router，如果可以自己定 router 就挺好，有这样一个库 https://github.com/vifird/react-keeper 基本兼容 react-router v4，但是有一些 react-router 所没有，但也一些挺有意义的功能。

按之前的用法，react-keeper 是很难用进去的。但如果把 router 解构了，那倒是方便了。而且也不一定所有人（例如我）都觉得 router 的状态有必要放进 store 中。。。

**Comment by llh911001** [comment]
已经更新，[commit](https://github.com/mirrorjs/mirror/commit/00ecdbc44693636549d0d41ff2e4ae7dd6a09715)。

更多信息可查看[更新日志](https://github.com/mirrorjs/mirror/blob/master/CHANGES.md)。
