### ISSUE TITLE
一些外部依赖的 Action Creator 需要如何处理呢？

### ISSUE THREAD

**Issue by viko16** [mirrorjs/mirror#65]
就像 https://github.com/suciuvlad/redux-dialog#step-3 ，
当中的 `openDialog`, `closeDialog` 都是 Action Creator，需要用户手动去 `dispatch` 的，而不由 mirror 管理

所以我需要如何把这些绑到 `mirrorx.actions` 上呢？ 还是说我只能在 connect 里传 `mapDispatchToProps` 自行处理？

**Comment by llh911001** [comment]
对于一些额外的 reducer/action，首先你需要在 `mirror.defaults` 中指定你需要的 `reducer`；

然后，是的，如果想 dispatch 这些 reducer 相关的 action，那么需要手动调用 `dispatch`，由于 Mirror 没有将 `store` 或者 `dispatch` 暴露出去，那么目前的确是只能通过在 connect 里传 `mapDispatchToProps` 处理哈。
