### ISSUE TITLE
如何支持 IE

### ISSUE THREAD

**Issue by icuke** [mirrorjs/mirror#69]
mirrorx 里面用了数组 find 及 includes 等等方法导致 ie 报错

**Comment by yurizhang** [comment]
import一个polyfill

**Comment by llh911001** [comment]
这种情况下，的确是需要自己引入 `babel-runtime` 的

**Comment by icuke** [comment]
import polyfill 之后
1 配置 .babelrc
2 mirrorx 依赖里面的 model 扩充 [].find   

才能解决 ie10+

**Comment by HuYuee** [comment]
@icuke @yurizhang @llh911001 也就是说只能支持到ie10吗？

**Comment by llh911001** [comment]
不是，如果你加了 polyfill，那么可以到 IE8

**Comment by HuYuee** [comment]
@llh911001 ok！多谢！
