### ISSUE TITLE
路由的引用方式改变了？

### ISSUE THREAD

**Issue by ChiaJune** [mirrorjs/mirror#71]
通过这样：`import { Router } from 'mirrorx`引不到了，
以后要改成  `import { Router } from 'mirrorx/lib/router` 这样？

**Comment by llh911001** [comment]
现在还没有变。

未来将 Router 解耦之后，router 会成为一个 submodule，改为 `import { Router } from 'mirrorx/router'` 这样。具体可先看一下 `feature/router` 分支。

**Comment by ChiaJune** [comment]
升级到v0.2.8，貌似路由相关的组件已经引用不到了

**Comment by llh911001** [comment]
贴一下报错信息？

PS. 我在升级依赖的时候，注意到 react-router-redux@5.0.0.alpha-7 版本有 [bug](https://github.com/ReactTraining/react-router/issues/5637)，因此没有升级 react-router-redux，使用的版本还是 5.0.0.alpha-6。

不知道你遇到的问题是否是类似下面这样：

```js

    Cannot find module './selectors' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/react-router-redux/index.js:6:18)
```

如果是的话，那可能是你安装依赖的时候，安装了 react-router-redux@5.0.0.alpha-7

**Comment by ChiaJune** [comment]
没有报错，只是警告，因为我 `react-router-redux`还是5.0.0.alpha-6，警告信息如下图：

![](http://ww1.sinaimg.cn/large/0060lm7Tly1fknoqpanq2j31hc0ny41e.jpg)

注意看下图：

![](http://ww4.sinaimg.cn/large/0060lm7Tly1fknouftrlsj31hc0ndgpv.jpg)

**并没有导出路由相关的组件**，请您确认

**Comment by llh911001** [comment]
我明白了。是我的疏忽，在 `npm publish` 时候，将 `feature/router` 分支中编译的代码给 publish 了。

抱歉，我这就修正一下，可能要麻烦你再升级一次版本了。

**Comment by llh911001** [comment]
已经重新 publish，请重新升级哈。谢谢反馈！

**Comment by ChiaJune** [comment]
不用客气。刚才升级试了一下，已经没问题了！
