### ISSUE TITLE
typescript何时可以支持?

### ISSUE THREAD

**Issue by publicHan** [mirrorjs/mirror#73]

**Comment by llh911001** [comment]
近期会支持的。

**Comment by publicHan** [comment]
工作量1个小时可以完成?

**Comment by llh911001** [comment]
开源不是给别人做外包哦，同学。

有什么需求和建议，可以礼貌提出；如果有可能的话，也可以自己参与贡献，提 Pull request。

而直接揣测一个功能的工作量以及所需的时间，是不礼貌的做法哈。

**Comment by publicHan** [comment]
请问若支持 Redux DevTools 要在mirror.model加window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__() 若用第三方的 middleware 需要在mirror.defaults(options)加?请问Redux DevTools能否直接给封装到mirror里面?

**Comment by llh911001** [comment]
1. Redux DevTools 的 middleware 内部已经封装好了，**不需要**你手动指定；
2. 额外的第三方 middleware **需要**通过 `mirror.defaults` 指定。

**Comment by publicHan** [comment]
FAQ 下关于Redux DevTools扩展的介绍是刚添加的?

**Comment by llh911001** [comment]
不是。

**Comment by publicHan** [comment]
感谢答复
