### ISSUE TITLE
在Android4.4下的浏览器不能正常使用

### ISSUE THREAD

**Issue by OldKinn** [mirrorjs/mirror#74]
在Android4.4下面，界面无法显示，能否告知一下支持的浏览器版本

**Comment by llh911001** [comment]
是否可以查看具体的出错信息？

另外，非常中肯的建议，我们会把浏览器的支持信息加上。

**Comment by OldKinn** [comment]
无法查看Android4.4的浏览器的异常信息，使用babel-polyfill处理后可以了，非常感谢！
