### ISSUE TITLE
react-router v4没有提供路由拦截的功能？

### ISSUE THREAD

**Issue by agileago** [mirrorjs/mirror#78]
比如我在 `/foo`路由下，要跳转到 `/user`下，我需要检查他登录了没有才能让他进到 `/user`下，好像没有办法可以实现这个功能.

**Comment by llh911001** [comment]
看 `react-router` v4 的文档，可以找到的哈，[`Prompt`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Prompt.md) 似乎可以满足你的需求。

**Comment by agileago** [comment]
![image](https://user-images.githubusercontent.com/11799110/32694346-7a9ed1e6-c778-11e7-9b2d-aff57168a5b4.png)
就这个，我觉得是 `react-router`团队偷懒了，强项使用confirm进行阻塞处理，根本满足不了需求，再说这个是离开页面的提示，起始需要的是进入页面之前得钩子，类似于这种
```javascript
router.beforeEach(async (to, from , next) => {
  if (await validateAuth()) {
    next()
  } else {
    next('/login')
  }
})
```
翻了半天文档也没找到怎么做，这么常见的一个需求，难道就没人遇到么

**Comment by llh911001** [comment]
confirm 是默认行为，你可以自定义的：https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/BrowserRouter.md#getuserconfirmation-func

**Comment by ChiaJune** [comment]
你想要的是这种吧？（猜一下，是权限认证？）
[http://reacttraining.cn/web/example/auth-workflow](http://reacttraining.cn/web/example/auth-workflow)
或
[https://github.com/bernabe9/react-router-v4-auth-example](https://github.com/bernabe9/react-router-v4-auth-example)

`react-router v4`跟以前的版本有很大变化，已经没有那些钩子函数了

**Comment by agileago** [comment]
@ChiaJune  这些例子都是进入到这个路由了(浏览器地址已经变成那个路由了),然后在里面的 `componentDidMount` 做异步判断，这种当然好做， 其实我想要的是你点击一个按钮相当于调用 `history.push('/foo')`,此时浏览器地址还没变化， 然后应该有个异步hook队列，可以注册进去异步函数，进行一些操作，比如权限判断能不能进入这样子， 不能进入的话就直接 `next(false)`, 可以进入的话 `next()` 就行了，这个时候浏览器地址才响应这个变化， 之前做项目都是用的`vue-router`，vue-router提供了很多这样的钩子去处理，然后现在做的这个`react`项目，路由突然就没有这些钩子了，简直就是半残疾的路由，不知到`react`社区是如何忍受的.  然后发现 `react-keeper` https://github.com/vifird/react-keeper 这个路由库，貌似解决了很多工程上的问题, 然后就想问问你们，难道做`react`的项目的时候没有遇到这些问题？

**Comment by ChiaJune** [comment]
其实你这种我之前在react-router的issue中看到过相关的讨论，好像做法就是自己来控制路由跳转，当然这样做是比较麻烦的。我之前也是用vue的，后来转到react，不过现在看来我更喜欢react，因为生态很强大，足够灵活（这一句是废话）。个人觉得这个不是忍受不忍受的问题，而是思想不同罢了（个人愚见）

**Comment by agileago** [comment]
对应的是代码量激增😃

**Comment by agileago** [comment]
最后我打算放弃这个功能了，改为在全局的ajax那里拦截一下，如果返回code为401就跳到登录😤😤😭

**Comment by ChiaJune** [comment]
@agileago 我就是这样搞的😃

**Comment by wall-wxk** [comment]
如果是链接点击跳转，可以用`e.preventDefault();`解决，简单粗暴😃

**Comment by zqinmiao** [comment]
@agileago 请问你最后解决了吗？我现在也同样遇到了你说的场景。想要在路由跳转之前发送异步请求看是否有权限。

**Comment by h2oiswater** [comment]
1. 使用connected-react-router
2. 添加中间件，拦截跳转Action
3. 判断是否登陆

**Comment by jimixy** [comment]
this.props.history.block((location, action) => {
                Modal.confirm({
                    title: '离开提示',
                    content: '当前修改的内容尚未保存，是否确认离开?',
                    keyboard: false,
                    onCancel: () => {},
                    onOk: () => {
                        self.clearnBlock();
                        this.props.history.push(location.pathname);
                    }
                });
            });

**Comment by Flcwl** [comment]
You can overrid a new method wraps the original method~

```js
const push = history.push
const replace = history.replace
const beforeEachEnter = (to, next) => {
  // do something...
  console.log(to)

  next(to)
}

history.push = (to) => {
  beforeEachEnter(to, push)
}

history.replace = (to) => {
  beforeEachEnter(to, replace)
}
```
