### ISSUE TITLE
关于 Array.prototype.find 的兼容性问题

### ISSUE THREAD

**Issue by biuuu** [mirrorjs/mirror#80]
https://github.com/mirrorjs/mirror/blob/dd3f659f4bb3295ef60bb4decde61a33ac1b9c10/src/model.js#L40
好像只看到用了这一个 ES6 的数组方法，
是否可以考虑用 ES5 的方法代替。

**Comment by llh911001** [comment]
嗯，在 `src/defatults.js` 中还用到了 `Array.prototype.includes` 方法，如果要考虑到这些 ES6 的兼容，可能要做的事情比较多了。

建议你引入一个 polyfill 哈。
