### ISSUE TITLE
请问mirror.default有详细一点的试例吗

### ISSUE THREAD

**Issue by tz310200** [mirrorjs/mirror#81]
我有个 reducers 方法多个模块复用，mirror.default可以实现统一配置这个方法吗
    reducers: {
        setState(state, data) {
            return {
                ...state,
                ...data,
                loading: false
            }
        }
}

**Comment by llh911001** [comment]
可以的啊，具体看[文档](https://github.com/mirrorjs/mirror/blob/master/docs/zh/api.md#-optionsreducers)哦。

**Comment by tz310200** [comment]
我按照文档

import mirror from 'mirrorx'

mirror.defaults({
    reducers: {
        classManagerList: test
    }
})


function test(state, data) {
    return {
        ...state,
        ...data,
        loadingClass:false
    }
}
actions打印出来classManagerList没有test方法是不是我写法有问题？

**Comment by llh911001** [comment]
不是，通过 `mirror.defaults` 指定的  `reducers` 是**标准的 reducer**，不会出现在 `actions` 对象上，只能通过标准的 `dispatch` 来触发其对应的 `action`  。

**Comment by tz310200** [comment]
那有办法把多个组件复用的方法提取出来，然后自动放置到需要组件的reducers下吗
因为我每个组件有几个相同的reducers方法

**Comment by llh911001** [comment]
@tz310200 可以的。可以参考我在一个 PR 里的回答：https://github.com/mirrorjs/mirror/pull/86#issuecomment-350545973
