### ISSUE TITLE
【help】 electron-react-boilerplate 改造为使用 mirror

### ISSUE THREAD

**Issue by chenkaiC4** [mirrorjs/mirror#85]
这个库非常棒，节省了很多写redux结构性代码的时间。

最近做electron开发，想用 [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) 初始化项目，但是在引入 mirrorjs 时，出现问题。

目前我的做法是，把 render，Route 这些关键词都替换为 mirrox 的。但是在dev模式下，不能刷新。刷新后界面为空，redux devtool 提示 ”no store found. Make sure to follow the instructions.”。这种情况下，hot reload 还有，但是手动刷新后，界面为空，需要重启。

我把代码提交在[这里](https://github.com/chenkaiC4/electron-react-boilerplate-use-mirrorx)，欢迎commit或者PR，纠正错误。感谢！

- 目前，原有的交互功能都ok，但我在 app/index.js 中的代码处理很糙，我直接忽略了原先的 store，只用了 app/routes.js 作为 render 的第一个参数。这肯定会导致 redux devtool 没有被配置。

但为什么手动刷新界面后，会白屏，假死，还没找到原因

**Comment by llh911001** [comment]
@chenkaiC4 问题解决了？
