### ISSUE TITLE
typescript支持啊?

### ISSUE THREAD

**Issue by publicHan** [mirrorjs/mirror#87]
typescript支持啊?

**Comment by llh911001** [comment]
我们团队的小伙伴已经提交 [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22095) 了呢，这几天就会被 DefinitelyTyped 官方合并了，合并后就可以了哈

**Comment by publicHan** [comment]
那些d.ts文件现在能放出来么. 晚上敲一敲demo

**Comment by llh911001** [comment]
可以看看这个仓库噢：https://github.com/Aaronphy/typings-mirrorx。

现在的 PR 还有一些 code style 的问题要解决，其他的没问题了。

**Comment by publicHan** [comment]
axios 能默认集成到项目里面?

**Comment by llh911001** [comment]
目前不打算集成。请求库的选择比较多，我们还是希望保持一个灵活性和精简度。

**Comment by publicHan** [comment]
谢谢回复

**Comment by llh911001** [comment]
@publicHan  今天已经正式支持了哈，npm：https://www.npmjs.com/package/@types/mirrorx
