### ISSUE TITLE
请问可以支持到react native上吗？

### ISSUE THREAD

**Issue by rainrcn** [mirrorjs/mirror#88]
如题

**Comment by rainrcn** [comment]
感觉现在的render和dom绑的有点过紧了，能否拆一下，还有router必须绑在框架里吗？

**Comment by llh911001** [comment]
先说 `render` 的问题。`render` 我们的初衷就是保持与 `ReactDOM.render` 一致的行为，接口和返回值都一致，哪怕中间其实做了 Redux 的 store 创建等操作。无论如何，是希望跟原有的 `ReactDOM.render`  行为一致。

另外 `react-router`，我们已经打算将它解耦了，近期会发布一版，将 router 解耦。

**Comment by rainrcn** [comment]
@llh911001 好吧=。=，我只是觉得要用绑ReactDOM的话，在ReactNative中想用就麻烦了

**Comment by llh911001** [comment]
这的确是个问题，后期我们再考虑下如何支持 React Native 哈。

**Comment by limitLiu** [comment]
@llh911001  用这个库做 React Native 好长时间了😂

**Comment by rainrcn** [comment]
@limitLiu  厉害！~ 敢问有没有例子哦。。

**Comment by limitLiu** [comment]
@rainrcn 我这个礼拜六看看有没有时间整一个例子给你参考一下

**Comment by WebPuY** [comment]
@rainrcn 请问您将mirror应用到RN了吗？react-dom问题如何解决的？

**Comment by limitLiu** [comment]
@rainrcn   @WebPuY    一个我自己修改后的例子 https://github.com/limitLiu/react-native-mirror
