### ISSUE TITLE
不支持IE吗

### ISSUE THREAD

**Issue by mastretail4git** [mirrorjs/mirror#91]
按照教程创建一个简单的应用，Chrome可以正常运行，IE出错
具体错误如下：
--------------------------
  47 |   throw new Error('Model name can not be "routing", it is used by react-router-redux!');
  48 | }
  49 | 
> 50 | if (models.find(function (item) {
  51 |   return item.name === name;
  52 | })) {
  53 |   throw new Error('Model "' + name + '" has been created, please select another name!');
----------------------
models.find方法不存在

**Comment by llh911001** [comment]
`find` 方法是 ES6 数组的原型方法，不支持 IE 呢。参考链接：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

你可以引入一个 polyfill 哈。
