### ISSUE TITLE
请问有没有打算搞服务器端渲染

### ISSUE THREAD

**Issue by limitLiu** [mirrorjs/mirror#97]
> 因为之前一直用这个搞 React Native 感觉非常好使 但是也就没在意服务器端渲染
但是最近搞一个 PC 端的网站 所以考虑到 SEO 问题

个么问题来了 你们有搞服务器端渲染方面的打算吗

**Comment by llh911001** [comment]
SSR 的具体方案一直思考当中，现在还没有特别好的想法。

目前是有这个打算，可能会伴随着一些 API 的改变
